import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

abstract class AppIcons {
  static const IconData arrowForward = CupertinoIcons.forward;
  static const IconData arrowBackward = CupertinoIcons.back;
  static const IconData close = CupertinoIcons.xmark;
  static const IconData bubbleSquare = CupertinoIcons.bubble_left;
  static const IconData bubbleSquareFilled = CupertinoIcons.bubble_left_fill;
  static const IconData megaPhone = Icons.campaign_outlined;
  static const IconData megaPhoneFilled = Icons.campaign_rounded;
  static const IconData group = CupertinoIcons.person_2;
  static const IconData groupFilled = CupertinoIcons.person_2_fill;
  static const IconData profileCircle = CupertinoIcons.profile_circled;
  static const IconData home = CupertinoIcons.house;
  static const IconData homeFilled = CupertinoIcons.house_fill;
  static const IconData search = CupertinoIcons.search;
  static const IconData add = CupertinoIcons.add;
  static const IconData personPlusFilled =
      CupertinoIcons.person_badge_plus_fill;
  static const IconData personPlus = CupertinoIcons.person_badge_plus;
  static const IconData settings = CupertinoIcons.gear;
  static const IconData edit = CupertinoIcons.square_pencil;
  static const IconData champion = Icons.emoji_events_outlined;
  static const IconData gallery = CupertinoIcons.photo_fill_on_rectangle_fill;
  static const IconData saved = CupertinoIcons.bookmark;
  static const IconData savedFilled = CupertinoIcons.bookmark_fill;
  static const IconData share = CupertinoIcons.share;
  static const IconData shareFilled = CupertinoIcons.share_solid;
  static const IconData control = CupertinoIcons.settings;
  static const IconData block = CupertinoIcons.nosign;
  static const IconData notification = CupertinoIcons.bell;
  static const IconData info = CupertinoIcons.info;
  static const IconData support = CupertinoIcons.headphones;
  static const IconData notificationFilled = CupertinoIcons.bell_fill;
  static const IconData paintBrush = CupertinoIcons.paintbrush;
  static const IconData translate = Icons.translate;
  static const IconData privacyPolicy = CupertinoIcons.checkmark_shield;
  static const IconData attach = CupertinoIcons.paperclip;
  static const IconData send = Icons.send;
  static const IconData photo = CupertinoIcons.photo_fill;
  static const IconData menuVert = CupertinoIcons.ellipsis_vertical;
  static const IconData lamp = CupertinoIcons.lightbulb;
  static const IconData lampFilled = CupertinoIcons.lightbulb_fill;
  static const IconData darkTheme = CupertinoIcons.moon_fill;
  static const IconData lightTheme = CupertinoIcons.sun_max_fill;
  static const IconData check = CupertinoIcons.checkmark;
  static const IconData checkCircle = CupertinoIcons.check_mark_circled;
  static const IconData arrowDown = CupertinoIcons.arrow_down;
  static const IconData male = Icons.male;
  static const IconData female = Icons.female;
  static const IconData nonBinary = Icons.transgender;
  static const IconData calender = CupertinoIcons.calendar;
  static const IconData phone = CupertinoIcons.device_phone_portrait;
  static const IconData warning = CupertinoIcons.exclamationmark_triangle;
  static const IconData error = CupertinoIcons.exclamationmark_circle;
  static const IconData pin = CupertinoIcons.pin;
  static const IconData unPin = CupertinoIcons.pin_slash;
  static const IconData delete = CupertinoIcons.delete;
  static const IconData deleteFilled = CupertinoIcons.delete_solid;
  static const IconData archived = CupertinoIcons.archivebox;
  static const IconData move = CupertinoIcons.move;
  static const IconData copy = CupertinoIcons.doc_on_clipboard;
  static const IconData reply = CupertinoIcons.arrowshape_turn_up_left_fill;
  static const IconData forward = CupertinoIcons.arrowshape_turn_up_right_fill;
}
